#!/bin/bash
# scripts/anomaly_detection/MSL/
. scripts/anomaly_detection/MSL/Autoformer.sh
. scripts/anomaly_detection/MSL/Crossformer.sh
. scripts/anomaly_detection/MSL/DLinear.sh
. scripts/anomaly_detection/MSL/ETSformer.sh
. scripts/anomaly_detection/MSL/FEDformer.sh
. scripts/anomaly_detection/MSL/FiLM.sh
. scripts/anomaly_detection/MSL/Informer.sh
. scripts/anomaly_detection/MSL/LightTS.sh
. scripts/anomaly_detection/MSL/MICN.sh
. scripts/anomaly_detection/MSL/Pyraformer.sh
. scripts/anomaly_detection/MSL/Reformer.sh
. scripts/anomaly_detection/MSL/TimesNet.sh
. scripts/anomaly_detection/MSL/Transformer.sh
. scripts/anomaly_detection/MSL/iTransformer.sh
# scripts/anomaly_detection/PSM/
. scripts/anomaly_detection/PSM/Autoformer.sh
. scripts/anomaly_detection/PSM/DLinear.sh
. scripts/anomaly_detection/PSM/TimesNet.sh
. scripts/anomaly_detection/PSM/Transformer.sh
# scripts/anomaly_detection/SMAP/
. scripts/anomaly_detection/SMAP/Autoformer.sh
. scripts/anomaly_detection/SMAP/TimesNet.sh
. scripts/anomaly_detection/SMAP/Transformer.sh
# scripts/anomaly_detection/SMD/
. scripts/anomaly_detection/SMD/Autoformer.sh
. scripts/anomaly_detection/SMD/TimesNet.sh
. scripts/anomaly_detection/SMD/Transformer.sh
# scripts/anomaly_detection/SWAT/
. scripts/anomaly_detection/SWAT/Autoformer.sh
. scripts/anomaly_detection/SWAT/TimesNet.sh
. scripts/anomaly_detection/SWAT/Transformer.sh
