#!/bin/bash
# scripts/imputation/ECL_script/
. scripts/imputation/ECL_script/Autoformer.sh
. scripts/imputation/ECL_script/DLinear.sh
. scripts/imputation/ECL_script/ETSformer.sh
. scripts/imputation/ECL_script/FEDformer.sh
. scripts/imputation/ECL_script/Informer.sh
. scripts/imputation/ECL_script/LightTS.sh
. scripts/imputation/ECL_script/Pyraformer.sh
. scripts/imputation/ECL_script/Reformer.sh
. scripts/imputation/ECL_script/TimesNet.sh
. scripts/imputation/ECL_script/Transformer.sh
. scripts/imputation/ECL_script/iTransformer.sh
# scripts/imputation/ETT_script/
. scripts/imputation/ETT_script/Autoformer_ETTh1.sh
. scripts/imputation/ETT_script/Autoformer_ETTh2.sh
. scripts/imputation/ETT_script/Autoformer_ETTm1.sh
. scripts/imputation/ETT_script/Autoformer_ETTm2.sh
. scripts/imputation/ETT_script/Crossformer_ETTh1.sh
. scripts/imputation/ETT_script/DLinear_ETTh1.sh
. scripts/imputation/ETT_script/FiLM_ETTh1.sh
. scripts/imputation/ETT_script/MICN_ETTh1.sh
. scripts/imputation/ETT_script/Nonstationary_Transformer_ETTh1.sh
. scripts/imputation/ETT_script/TiDE_ETTh1.sh
. scripts/imputation/ETT_script/TimesNet_ETTh1.sh
. scripts/imputation/ETT_script/TimesNet_ETTh2.sh
. scripts/imputation/ETT_script/TimesNet_ETTm1.sh
. scripts/imputation/ETT_script/TimesNet_ETTm2.sh
. scripts/imputation/ETT_script/Transformer_ETTh1.sh
. scripts/imputation/ETT_script/Transformer_ETTh2.sh
. scripts/imputation/ETT_script/Transformer_ETTm1.sh
. scripts/imputation/ETT_script/Transformer_ETTm2.sh
. scripts/imputation/ETT_script/iTransformer_ETTh2.sh
# scripts/imputation/Weather_script/
. scripts/imputation/Weather_script/Autoformer.sh
. scripts/imputation/Weather_script/TimesNet.sh
. scripts/imputation/Weather_script/Transformer.sh
