#!/bin/bash
# scripts/long_term_forecast/ECL_script/
. scripts/long_term_forecast/ECL_script/Autoformer.sh
. scripts/long_term_forecast/ECL_script/Crossformer.sh
. scripts/long_term_forecast/ECL_script/DLinear.sh
. scripts/long_term_forecast/ECL_script/ETSformer.sh
. scripts/long_term_forecast/ECL_script/FEDformer.sh
. scripts/long_term_forecast/ECL_script/FiLM.sh
. scripts/long_term_forecast/ECL_script/Informer.sh
. scripts/long_term_forecast/ECL_script/Koopa.sh
. scripts/long_term_forecast/ECL_script/LightTS.sh
. scripts/long_term_forecast/ECL_script/MICN.sh
. scripts/long_term_forecast/ECL_script/Nonstationary_Transformer.sh
. scripts/long_term_forecast/ECL_script/PatchTST.sh
. scripts/long_term_forecast/ECL_script/Pyraformer.sh
. scripts/long_term_forecast/ECL_script/Reformer.sh
. scripts/long_term_forecast/ECL_script/TimesNet.sh
. scripts/long_term_forecast/ECL_script/Transformer.sh
. scripts/long_term_forecast/ECL_script/iTransformer.sh
# scripts/long_term_forecast/ETT_script/
. scripts/long_term_forecast/ETT_script/Autoformer_ETTh1.sh
. scripts/long_term_forecast/ETT_script/Autoformer_ETTh2.sh
. scripts/long_term_forecast/ETT_script/Autoformer_ETTm1.sh
. scripts/long_term_forecast/ETT_script/Autoformer_ETTm2.sh
. scripts/long_term_forecast/ETT_script/Crossformer_ETTh1.sh
. scripts/long_term_forecast/ETT_script/Crossformer_ETTh2.sh
. scripts/long_term_forecast/ETT_script/Crossformer_ETTm1.sh
. scripts/long_term_forecast/ETT_script/Crossformer_ETTm2.sh
. scripts/long_term_forecast/ETT_script/DLinear_ETTh1.sh
. scripts/long_term_forecast/ETT_script/ETSformer_ETTh1.sh
. scripts/long_term_forecast/ETT_script/FEDformer_ETTh1.sh
. scripts/long_term_forecast/ETT_script/FiLM_ETTh1.sh
. scripts/long_term_forecast/ETT_script/FiLM_ETTh2.sh
. scripts/long_term_forecast/ETT_script/FiLM_ETTm1.sh
. scripts/long_term_forecast/ETT_script/FiLM_ETTm2.sh
. scripts/long_term_forecast/ETT_script/Informer_ETTh1.sh
. scripts/long_term_forecast/ETT_script/Koopa_ETTh1.sh
. scripts/long_term_forecast/ETT_script/Koopa_ETTh2.sh
. scripts/long_term_forecast/ETT_script/Koopa_ETTm1.sh
. scripts/long_term_forecast/ETT_script/Koopa_ETTm2.sh
. scripts/long_term_forecast/ETT_script/LightTS_ETTh1.sh
. scripts/long_term_forecast/ETT_script/MICN_ETTh1.sh
. scripts/long_term_forecast/ETT_script/MICN_ETTh2.sh
. scripts/long_term_forecast/ETT_script/MICN_ETTm1.sh
. scripts/long_term_forecast/ETT_script/MICN_ETTm2.sh
. scripts/long_term_forecast/ETT_script/Nonstationary_Transformer_ETTh1.sh
. scripts/long_term_forecast/ETT_script/Nonstationary_Transformer_ETTh2.sh
. scripts/long_term_forecast/ETT_script/Nonstationary_Transformer_ETTm1.sh
. scripts/long_term_forecast/ETT_script/Nonstationary_Transformer_ETTm2.sh
. scripts/long_term_forecast/ETT_script/PatchTST_ETTh1.sh
. scripts/long_term_forecast/ETT_script/PatchTST_ETTh2.sh
. scripts/long_term_forecast/ETT_script/PatchTST_ETTm1.sh
. scripts/long_term_forecast/ETT_script/PatchTST_ETTm2.sh
. scripts/long_term_forecast/ETT_script/Pyraformer_ETTh1.sh
. scripts/long_term_forecast/ETT_script/Pyraformer_ETTh2.sh
. scripts/long_term_forecast/ETT_script/Pyraformer_ETTm1.sh
. scripts/long_term_forecast/ETT_script/Pyraformer_ETTm2.sh
. scripts/long_term_forecast/ETT_script/Reformer_ETTh1.sh
. scripts/long_term_forecast/ETT_script/TiDE_ETTh1.sh
. scripts/long_term_forecast/ETT_script/TimesNet_ETTh1.sh
. scripts/long_term_forecast/ETT_script/TimesNet_ETTh2.sh
. scripts/long_term_forecast/ETT_script/TimesNet_ETTm1.sh
. scripts/long_term_forecast/ETT_script/TimesNet_ETTm2.sh
. scripts/long_term_forecast/ETT_script/Transformer_ETTh1.sh
. scripts/long_term_forecast/ETT_script/Transformer_ETTh2.sh
. scripts/long_term_forecast/ETT_script/Transformer_ETTm1.sh
. scripts/long_term_forecast/ETT_script/Transformer_ETTm2.sh
. scripts/long_term_forecast/ETT_script/iTransformer_ETTh2.sh
# scripts/long_term_forecast/Exchange_script/
. scripts/long_term_forecast/Exchange_script/Autoformer.sh
. scripts/long_term_forecast/Exchange_script/Crossformer.sh
. scripts/long_term_forecast/Exchange_script/FiLM.sh
. scripts/long_term_forecast/Exchange_script/Koopa.sh
. scripts/long_term_forecast/Exchange_script/MICN.sh
. scripts/long_term_forecast/Exchange_script/Nonstationary_Transformer.sh
. scripts/long_term_forecast/Exchange_script/PatchTST.sh
. scripts/long_term_forecast/Exchange_script/Pyraformer.sh
. scripts/long_term_forecast/Exchange_script/TimesNet.sh
. scripts/long_term_forecast/Exchange_script/Transformer.sh
# scripts/long_term_forecast/ILI_script/
. scripts/long_term_forecast/ILI_script/Autoformer.sh
. scripts/long_term_forecast/ILI_script/Crossformer.sh
. scripts/long_term_forecast/ILI_script/FiLM.sh
. scripts/long_term_forecast/ILI_script/Koopa.sh
. scripts/long_term_forecast/ILI_script/MICN.sh
. scripts/long_term_forecast/ILI_script/Nonstationary_Transformer.sh
. scripts/long_term_forecast/ILI_script/PatchTST.sh
. scripts/long_term_forecast/ILI_script/TimesNet.sh
. scripts/long_term_forecast/ILI_script/Transformer.sh
# scripts/long_term_forecast/Traffic_script/
. scripts/long_term_forecast/Traffic_script/Autoformer.sh
. scripts/long_term_forecast/Traffic_script/Crossformer.sh
. scripts/long_term_forecast/Traffic_script/FiLM.sh
. scripts/long_term_forecast/Traffic_script/Koopa.sh
. scripts/long_term_forecast/Traffic_script/MICN.sh
. scripts/long_term_forecast/Traffic_script/Nonstationary_Transformer.sh
. scripts/long_term_forecast/Traffic_script/PatchTST.sh
. scripts/long_term_forecast/Traffic_script/Pyraformer.sh
. scripts/long_term_forecast/Traffic_script/TimesNet.sh
. scripts/long_term_forecast/Traffic_script/Transformer.sh
. scripts/long_term_forecast/Traffic_script/iTransformer.sh
# scripts/long_term_forecast/Weather_script/
. scripts/long_term_forecast/Weather_script/Autoformer.sh
. scripts/long_term_forecast/Weather_script/Crossformer.sh
. scripts/long_term_forecast/Weather_script/FiLM.sh
. scripts/long_term_forecast/Weather_script/MICN.sh
. scripts/long_term_forecast/Weather_script/Nonstationary_Transformer.sh
. scripts/long_term_forecast/Weather_script/PatchTST.sh
. scripts/long_term_forecast/Weather_script/Pyraformer.sh
. scripts/long_term_forecast/Weather_script/TimesNet.sh
. scripts/long_term_forecast/Weather_script/Transformer.sh
. scripts/long_term_forecast/Weather_script/iTransformer.sh
